name: Build & Push Build Image To ReSim
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: resimai/core:latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ECR
        uses: docker/login-action@v2
        with:
          registry: 450373242995.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push
        run: |
            ./resim/examples/sim_runner/build.sh
            docker tag sim_runner:latest 450373242995.dkr.ecr.us-east-1.amazonaws.com/simbox-tests:github-latest
            # aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 450373242995.dkr.ecr.us-east-1.amazonaws.com
            docker push 450373242995.dkr.ecr.us-east-1.amazonaws.com/simbox-tests:github-latest
            ./resim/examples/sim_runner/test_run.sh
